# Generated by Django 4.2.5 on 2023-10-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=222)),
                ("image", models.ImageField(upload_to="pics")),
                ("desc", models.TextField()),
            ],
        ),
    ]
