# Generated by Django 4.2.5 on 2023-10-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapplication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="my_team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="pho")),
                ("detalis", models.TextField()),
                ("id_num", models.IntegerField()),
            ],
        ),
    ]
